INSERT INTO DRONES (SERIAL_NUMBER,MODEL,WEIGHT,BATTERY_CAPACITY, STATE) VALUES ('serial1','LIGHTWEIGHT',0,60, 'IDLE');
INSERT INTO DRONES (SERIAL_NUMBER,MODEL,WEIGHT,BATTERY_CAPACITY, STATE) VALUES ('serial2','MIDDLEWEIGHT',0,20, 'IDLE');
INSERT INTO DRONES (SERIAL_NUMBER,MODEL,WEIGHT,BATTERY_CAPACITY, STATE) VALUES ('serial3','CRUISERWEIGHT',0,15, 'IDLE');
INSERT INTO DRONES (SERIAL_NUMBER,MODEL,WEIGHT,BATTERY_CAPACITY, STATE) VALUES ('serial4','HEAVYWEIGHT',0,70, 'IDLE');
INSERT INTO DRONES (SERIAL_NUMBER,MODEL,WEIGHT,BATTERY_CAPACITY, STATE) VALUES ('serial5','LIGHTWEIGHT',0,50, 'IDLE');
-- INSERT INTO MEDICATIONS (ID,NAME,WEIGHT,CODE,IMAGE, DRONE_ID) VALUES (1,'Med1',10,'MED_1','image1.jpg', 1);
INSERT INTO MEDICATIONS (CODE,NAME,WEIGHT,IMAGE) VALUES ('MED1','Med1name',20,'image1.jpg');
INSERT INTO MEDICATIONS (CODE,NAME,WEIGHT,IMAGE) VALUES ('MED2','Med2name',20,'image2.jpg');
INSERT INTO MEDICATIONS (CODE,NAME,WEIGHT,IMAGE) VALUES ('MED3','Med3name',20,'image3.jpg');


